# BUILDER
FROM golang:1.16 AS builder
WORKDIR /go-build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -mod=vendor -a -o /go-build/zigbee-gw .

# RUNNER
FROM alpine:3.12
WORKDIR /usr/local/bin
COPY --from=builder /go-build/zigbee-gw .

# it does accept the variable $SERVICE
CMD ["zigbee-gw"]

# Upload to Docker Hub
# docker build -f Dockerfile.linux-armv7 -t redkite/zigbee-gw:latest-linux-armv7 .
# docker push redkite/zigbee-gw:latest-linux-armv7